### ISSUE TITLE
Bintray binary not available any longer

### ISSUE THREAD

**Issue by LinqLover** [cmfcmf/MagicMouse#12]
Maybe store the binary as a GitHub release instead?

**Comment by cmfcmf** [comment]
Yeah, that's definitely a good idea. I have warnings from Bintray in my inbox about the service shutting down, which I ignored for far too long 🙈 
![image](https://user-images.githubusercontent.com/2145092/144710774-806ee2ed-d9d6-43ae-9878-7bf820c86094.png)

**Comment by cmfcmf** [comment]
I'll look into it 👍

**Comment by cmfcmf** [comment]
Done :) MagicMouse should now also work with Squeak 5.3 again (in addition to trunk).

**Comment by LinqLover** [comment]
Thank you! If you tested it with Trunk, you did not test it on Linux/macOS, did you? Afaik @tom95 is currently fixing a bug in the AIO plugin which has been preventing MM from working for a few days.

**Comment by cmfcmf** [comment]
Ah, sorry, my comment was misleading, I only tested it in Squeak5.3.
